version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    cooldown:
      default-days: 1

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    cooldown:
      default-days: 1

  - package-ecosystem: "npm"
    directory: "/e2e/"
    schedule:
      interval: "weekly"
      day: "friday"
    groups:
      appium:
        patterns:
          - "appium*"
      webdriverio:
        patterns:
          - "webdriverio"
          - "@wdio/types"
    cooldown:
      default-days: 1
