excluded:
  - Pods
  - vendor

disabled_rules:
  - force_cast
  - block_based_kvo

line_length:
  warning: 200
  error: 300

identifier_name:
  min_length:
    warning: 1

trailing_comma:
  mandatory_comma: true

