default_platform(:ios)

platform :ios do

  private_lane :import_certificates_and_provisioning_profile do
    create_keychain(
        name: "ios_app_keychain",
        password: ENV["KEYCHAIN_PASSWORD"],
        timeout: 1800
    )
    import_certificate(
        certificate_path: "distribution.p12",
        certificate_password: ENV["CERTIFICATE_PASSWORD"],
        keychain_name: "ios_app_keychain",
        keychain_password: ENV["KEYCHAIN_PASSWORD"]
    )
    install_provisioning_profile(path: "distribution.mobileprovision")
  end

  desc "Submit a new Beta Build to App Distribution"
  lane :beta do
    import_certificates_and_provisioning_profile
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "SpoolDays.xcodeproj",
      code_sign_identity: "Apple Distribution",
      bundle_identifier: "org.codefirst.SpoolDays",
      profile_name: "SpoolDays App Distribution Adhoc deployment"
    )
    increment_build_number(
      build_number: ENV["BUILD_NUMBER"]
    )
    update_project_team(
      path: 'SpoolDays.xcodeproj',
      teamid: ENV['TEAM_ID'])
    build_app(
      scheme: 'SpoolDays',
      export_method: 'ad-hoc',
      export_options: {
        provisioningProfiles: {
          "org.codefirst.SpoolDays" => "SpoolDays App Distribution Adhoc deployment",
        }
      }
    )
    firebase_app_distribution(
      groups: ENV['APP_DISTRIBUTION_GROUP'],
      release_notes: ENV['APP_DISTRIBUTION_MESSAGE'] || 'Build')
    update_project_team(
      path: 'SpoolDays.xcodeproj',
      teamid: '')
  end

  desc "Build for simulator"
  lane :build_for_simulator do
    gym(
      scheme: "SpoolDays",
      sdk: "iphonesimulator",
      archive_path: "./SpoolDays.xcarchive",
      skip_package_ipa: true,
      skip_codesigning: true,
      destination: "generic/platform=iOS Simulator"
    )
  end

  desc "Runt tests"
  lane :test do
    run_tests(
      scheme: "SpoolDays"
    )
  end
end
