name: 'Setup Xcode'
description: 'Sets the Xcode version using xcode-select'
inputs:
  version:
    description: 'Xcode version'
    required: true
    default: '26.4'

runs:
  using: "composite"
  steps:
    - name: Set Xcode version
      run: sudo xcode-select -s "/Applications/Xcode_$XCODE_VERSION.app"
      shell: bash
      env:
        XCODE_VERSION: ${{ inputs.version }}

    - name: Show Xcode version
      run: xcodebuild -version
      shell: bash
