name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
  push:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  swiftlint:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v6

      - name: GitHub Action for SwiftLint with --strict
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict

  swiftformat:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v6

      - name: Show Swift version
        run: swift --version

      - name: Run swift-format
        run: |
          find . -maxdepth 1 -type d -name 'SpoolDays*' ! -name '*.xcodeproj' -exec swift format lint --parallel --recursive --strict {} +

  build:
    needs: [swiftlint, swiftformat]
    if: github.event.pull_request.draft == false
    runs-on: macos-26
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v6

      - name: Set Xcode version
        uses: ./.github/actions/setup-xcode

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - uses: irgaly/xcode-cache@v1
        with:
          key: xcode-cache-deriveddata-${{ github.job }}-${{ github.workflow }}-${{ github.sha }}
          restore-keys: xcode-cache-deriveddata-${{ github.job }}-${{ github.workflow }}-
          swiftpm-cache-key: xcode-cache-sourcepackages-${{ github.job }}-${{ github.workflow }}-${{ github.sha }}
          swiftpm-cache-restore-keys: xcode-cache-sourcepackages-${{ github.job }}-${{ github.workflow }}-

      - name: Cache Pods
        uses: actions/cache@v5
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Pods
        run: bundle exec pod install

      - name: Build
        run: |
          bundle exec fastlane build_for_simulator
        env:
          FASTLANE_SKIP_UPDATE_CHECK: true

  test:
    needs: [swiftlint, swiftformat]
    if: github.event.pull_request.draft == false
    runs-on: macos-26
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v6

      - name: Set Xcode version
        uses: ./.github/actions/setup-xcode

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - uses: irgaly/xcode-cache@v1
        with:
          key: xcode-cache-deriveddata-${{ github.job }}-${{ github.workflow }}-${{ github.sha }}
          restore-keys: xcode-cache-deriveddata-${{ github.job }}-${{ github.workflow }}-
          swiftpm-cache-key: xcode-cache-sourcepackages-${{ github.job }}-${{ github.workflow }}-${{ github.sha }}
          swiftpm-cache-restore-keys: xcode-cache-sourcepackages-${{ github.job }}-${{ github.workflow }}-

      - name: Cache Pods
        uses: actions/cache@v5
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Pods
        run: |
          bundle exec pod install

      # https://github.com/actions/runner-images/issues/12777
      - name: Workaround for hanging simulator
        id: boot_simulator
        timeout-minutes: 12
        run: |
          brew install coreutils -q

          echo "Listing simulator devices:"
          DEVICE_ID=$(xcrun simctl list devices available -j | jq -r '
            .devices
            | to_entries
            | map(select(.key | contains("com.apple.CoreSimulator.SimRuntime.iOS")))
            | max_by(.key)
            | .value
            | .[]
            | select(.name | startswith("iPhone"))
            | .udid
          ' | head -n 1)
          echo "device_id=$DEVICE_ID" >> "$GITHUB_OUTPUT"
          echo "--------------------------------"
          echo "👀 Updating dyld_shared_cache:"
          xcrun simctl runtime dyld_shared_cache update --all
          echo "--------------------------------"
          echo "👀 Booting simulator: with ID: $DEVICE_ID"

          i=1
          max=5
          while [ $i -le $max ]; do
            echo "👀 Launching Simulator (Attempt $i/$max)"
            # Brewfile installs coreutils which includes gtimeout
            if gtimeout -s SIGKILL 2m xcrun simctl bootstatus "$DEVICE_ID" -b; then
              echo "✅ Simulator booted successfully"
              break
            else
              echo "❌ Simulator boot timed out. Shutting down..."
              xcrun simctl shutdown "$DEVICE_ID" || true # prevents "Unable to shutdown device in current state: Shutdown" error

              echo "🔁 Retrying in 5s..."
              i=$((i + 1))
              sleep 5
            fi
          done

          if [ $i -gt $max ]; then
            echo "::error::Failed to boot simulator after $max attempts."
            exit 1
          fi

      - name: Test
        run: |
          bundle exec fastlane scan --destination "id=$DEVICE_ID"
        env:
          DEVICE_ID: ${{ steps.boot_simulator.outputs.device_id }}
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 120
          FASTLANE_SKIP_UPDATE_CHECK: true
