name: Cleanup PR cache

on:
  pull_request:
    types:
      - closed

permissions: {}

jobs:
  cleanup:
    runs-on: ubuntu-slim
    timeout-minutes: 3
    permissions:
      actions: write
    steps:
      - name: Delete caches for this PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh cache delete --all --succeed-on-no-caches --repo "${{ github.repository }}" --ref "refs/pull/${{ github.event.pull_request.number }}/merge"
