name: Deploy

on:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
 build:

   runs-on: macos-26
   timeout-minutes: 20
   permissions:
     contents: read
   environment:
     name: AppDistribution

   steps:
   - uses: actions/checkout@v7

   - uses: jdx/mise-action@v4
     env:
       MISE_DISABLE_TOOLS: ruby

   - name: Set Xcode version
     uses: ./.github/actions/setup-xcode

   - uses: ruby/setup-ruby@v1
     with:
       bundler-cache: true

   - name: Setup p12 certificate file
     run: |
       echo "$CERTIFICATE" > distribution.p12.txt
       base64 --decode < distribution.p12.txt > distribution.p12
     env:
       CERTIFICATE: ${{ secrets.CERTIFICATE }}

   - name: Setup provisioning profile
     run: |
       echo "$PROVISIONING_PROFILE" > distribution.mobileprovision.txt
       base64 --decode < distribution.mobileprovision.txt > distribution.mobileprovision
     env:
       PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}

   - name: Setup GoogleService-Info.plist
     run: |
       echo "$GOOGLE_SERVICE_INFO_PLIST" > SpoolDays/GoogleService-Info.plist
     env:
       GOOGLE_SERVICE_INFO_PLIST: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}

   - name: Setup Service Account Private Key
     run: |
       echo "$GOOGLE_APPLICATION_CREDENTIALS" > service_account_private_key.json
     env:
       GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

   - name: Build and deploy to App Distribution
     env:
       BUILD_NUMBER: ${{ github.run_number }}
       TEAM_ID: ${{ secrets.TEAM_ID }}
       KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
       CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
       APP_DISTRIBUTION_GROUP: ${{ secrets.APP_DISTRIBUTION_GROUP }}
       APP_DISTRIBUTION_MESSAGE: ${{ github.sha }}
       GOOGLE_APPLICATION_CREDENTIALS: service_account_private_key.json
       MISE_DISABLE_TOOLS: ruby
       LICENSE_PLIST_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     run: mise run deploy
